name: Auto App Update

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
      - "v*"
  schedule:
    - cron: "0 11,18,21 * * 1-5"
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests
      run: |
        pip install requests
    - name: Read configs from secrets
      env:
        CONFIG_ID: ${{ secrets.CONFIG_ID }}
        CONFIG_KEY: ${{ secrets.CONFIG_KEY }}
      run: |
        python main.py
